In [1]:
import pandas as pd
import numpy as np
import matplotlib 
from IPython.display import display, HTML, FileLink

In [2]:
# Especifique a codificação ISO-8859-1 ao ler o arquivo CSV
df = pd.read_csv('usuarios.csv', encoding='ISO-8859-1')

In [3]:
df.info

<bound method DataFrame.info of             ID      Nome  Idade  \
0          105   marcelo     35
1          106      joao     45
2          107  fernanda     58
3          108     Lucas     25
4          101       BOB     25
5          102    Carlos     35
6          103       Eva     28
7          104     Lucas     45
8          109       BOB     25
9          110    Carlos     35
10         111       Eva     28
11         112     Lucas     45
12         109       BOB     25
13         110    Carlos     35
14         111       Eva     28
15         112     Lucas     45
16         113       BOB     25
17         114    Carlos     35
18         115       Eva     28
19         201     Lucas     45
20         117       BOB     25
21         118    Carlos     35
22         119       Eva     28
23         120     Lucas     45
24         121       BOB     25
25         122    Carlos     35
26         123       Eva     28
27         124     Lucas     45
28         125       BOB     25
29         126    Carlos     35
30         127       Eva     28
31         128     Lucas     45
32         129       BOB     25
33         130    Carlos     35
34  usuario_id      nome  idade
35         131       BOB     25
36         132    Carlos     35
37         133       Eva     28
38         134     Lucas     45

                                            Profissao   Renda  \
0                                   Analista de Dados  4500.0
1                                           Professor  3800.0
2   MÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ...  6000.0
3                                            Advogado  7500.0
4                                   Analista de Dados  4500.0
5                                           Professor  3800.0
6   MÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ...  6000.0
7                                            Advogado  7500.0
8                                   Analista de Dados  4500.0
9                                           Professor  3800.0
10  MÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ...  6000.0
11                                           Advogado  7500.0
12                                  Analista de Dados  4500.0
13                                          Professor  3800.0
14  MÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ...  6000.0
15                                           Advogado  7500.0
16                                  Analista de Dados  4500.0
17                                          Professor  3800.0
18  MÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ...  6000.0
19                                           Advogado  7500.0
20                                  Analista de Dados  4500.0
21                                          Professor  3800.0
22                              MÃÂÃÂÃÂÃÂ©dica  6000.0
23                                           Advogado  7500.0
24                                  Analista de Dados  4500.0
25                                          Professor  3800.0
26                                      MÃÂÃÂ©dica  6000.0
27                                           Advogado  7500.0
28                                  Analista de Dados  4500.0
29                                          Professor  3800.0
30                                      MÃÂÃÂ©dica  6000.0
31                                           Advogado  7500.0
32                                  Analista de Dados  4500.0
33                                          Professor  3800.0
34                                          profissao   renda
35                                  Analista de Dados  4500.0
36                                          Professor  3800.0
37                                             Médica  6000.0
38                                           Advogado  7500.0

                                             Mensagem
0   OlÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ...
1   Lembre-se de controlar seus gastos e fazer um ...
2   Investir em educaÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ...
3   Considere criar uma reserva de emergÃÂÃÂÃ...
4   Lembre-se de controlar seus gastos e fazer um ...
5   Investir em educaÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ...
6   Considere criar uma reserva de emergÃÂÃÂÃ...
7   Poupar regularmente ÃÂÃÂÃÂÃÂÃÂÃÂÃ...
8   Poupar regularmente ÃÂÃÂÃÂÃÂÃÂÃÂÃ...
9   OlÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ...
10  Lembre-se de controlar seus gastos e fazer um ...
11  Investir em educaÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ...
12  Poupar regularmente ÃÂÃÂÃÂÃÂÃÂÃÂÃ...
13  OlÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ...
14  Lembre-se de controlar seus gastos e fazer um ...
15  Investir em educaÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ...
16  Ensine educaÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ...
17  Economize em energia desligando dispositivos e...
18  Considere cozinhar em casa em vez de jantar fo...
19                escreva uma mensagem para o usuario
20  Reavalie seus planos de celular e internet par...
21  Resista a compras por impulso e pense antes de...
22  FaÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ§a um planeja...
23  OlÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡! Aqui estÃ...
24  Lembre-se de controlar seus gastos e fazer um ...
25  Investir em educaÃÂÃÂÃÂÃÂ§ÃÂÃÂÃÂÃ...
26  Considere criar uma reserva de emergÃÂÃÂÃ...
27  Poupar regularmente ÃÂÃÂÃÂÃÂ© uma ÃÂÃ...
28  Evite dÃÂÃÂÃÂÃÂ­vidas de cartÃÂÃÂÃ...
29  Pesquise e compare preÃÂÃÂÃÂÃÂ§os antes...
30  Automatize suas economias transferindo dinheir...
31  Reduza despesas desnecessÃÂÃÂÃÂÃÂ¡rias ...
32  Acompanhe seus gastos em um aplicativo finance...
33  Aprenda sobre investimentos e diversifique sua...
34                                           mensagem
35  EstabeleÃ§a metas financeiras de curto e longo...
36  Participe de programas de fidelidade para econ...
37  Ensine educaÃ§Ã£o financeira aos seus filhos p...
38  Economize em energia desligando dispositivos e...  >

In [4]:
df.head()

,ID,Nome,Idade,Profissao,Renda,Mensagem
0,105,marcelo,35,Analista de Dados,4500.0,OlÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ...
1,106,joao,45,Professor,3800.0,Lembre-se de controlar seus gastos e fazer um ...
2,107,fernanda,58,MÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ...,6000.0,Investir em educaÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ...
3,108,Lucas,25,Advogado,7500.0,Considere criar uma reserva de emergÃÂÃÂÃ...
4,101,BOB,25,Analista de Dados,4500.0,Lembre-se de controlar seus gastos e fazer um ...

In [24]:
import os
import pandas as pd


# Transformar os dados em uma tabela HTML com estilos CSS inline
html_table = df.to_html(classes='table', escape=False, index=False, table_id='my-table')

# Obter o diretório atual
current_dir = os.getcwd()

# Caminho para a pasta 'template' dentro do diretório atual
template_path = os.path.join(current_dir, 'flask', 'static')

# Verificar se a pasta 'template' existe, senão, crie-a
if not os.path.exists(template_path):
    os.makedirs(template_path)

# Abra o arquivo table.html para escrever o conteúdo
with open(os.path.join(template_path, 'table.html'), 'w', encoding='utf-8') as file:
    file.write('<html><head>')
    file.write('<style>')
    file.write('.table { border-collapse: collapse; width: 100%; }')
    file.write('.table, th, td { border: 5px solid black; padding: 8px; }')
    file.write('.center { text-align: center; }')  # Estilo CSS para centralizar
    file.write('</style>')
    file.write('</head><body>')

    # Centralize o título
    file.write('<h1 class="center">Minha Tabela de Usuários</h1>')




    # Inserir a tabela gerada
    file.write(html_table)

    file.write('</body></html>')